In [241]:
import pandas as pd
# import re
from scipy.spatial.distance import cdist
# import itertools
# import numpy as np
# from math import mode

In [242]:
trained = pd.read_csv("Tweets.csv")
test = pd.read_csv("Tweets_Test.csv")
# df.to_csv('existing.csv', mode='a', index=False, header=False)

In [243]:
trained['text'] = trained['text'].str.lower()
test['text'] = test['text'].str.lower()
trained.head()

Sentiment                                               text
0   neutral                @virginamerica what @dhepburn said.
1  positive  @virginamerica plus you've added commercials t...
2   neutral  @virginamerica i didn't today... must mean i n...
3  negative  @virginamerica it's really aggressive to blast...
4  negative  @virginamerica and it's a really big bad thing...

In [244]:
stopwords = []

with open("stopwords.txt", "r") as file:
    for every_line in file:
        for word in every_line.split():
            stopwords.append(word)
print(stopwords)

#List of all special characters that are to be removed.
special_chars = ["!",'"',"%","&","amp","'","(",")", "*","+",",","-",".",
                 "/",":",";","<","=",">","?","[","\"","]","^","_",
                 "`","{","|","}","~","–","@","#","$"]

['i', "i'm", 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 't

In [245]:
#Removed Stopwords
for i in range(len(trained['text'])):
    new = ""
    temp = trained['text'][i].split(" ")
    # print(temp)
    for j in temp:
        if j not in stopwords:
            new += j + " "
        # elif j not in
    trained['text'][i] = new[:-1]
trained.head()

Sentiment                                               text
0   neutral                     @virginamerica @dhepburn said.
1  positive  @virginamerica plus added commercials experien...
2   neutral  @virginamerica today... must mean need take an...
3  negative  @virginamerica really aggressive blast obnoxio...
4  negative                @virginamerica really big bad thing

In [246]:
#Removed Stop Words from Test DS:
for i in range(len(test['text'])):
    new = ""
    temp = test['text'][i].split(" ")
    # print(temp)
    for j in temp:
        if j not in stopwords:
            new += j + " "
        # elif j not in 
    test['text'][i] = new[:-1]
test.head()

C:\Users\EAM\AppData\Local\Temp\ipykernel_14792\594254565.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['text'][i] = new[:-1]


Sentiment                                               text  Predicted
0  negative  @usairways phl, btv today made deplane "it's s...        NaN
1  negative  @usairways things non-delayed flights na? get ...        NaN
2  negative  @usairways today,no reason 4 anyone approve me...        NaN
3   neutral                    @usairways look better service.        NaN
4  negative  @usairways customer service philly deplorable,...        NaN

In [247]:
#Removed Stopwords
trained['text'] = trained['text'].str.replace(r'http?://[^\s<>"]+|www\.[^\s<>"]+', '', regex = True) # Removing hyperlinks from all the tweets
trained['text'] = trained['text'].str.replace('@[A-Za-z0-9]+', '', regex = True) # Removing usernames from all the tweets.
trained['text'] = trained['text'].str.replace(r'\B#\w*[a-zA-Z]+\w*', '', regex = True) # Removing hashtags, including the text, from all the tweets
trained['text'] = trained['text'].str.replace('\d+', '', regex = True) # Removing numbers from all the tweets

for char in special_chars:
    trained['text'] = trained['text'].str.replace(char, '', regex = True)

test['text'] = test['text'].str.replace(r'http?://[^\s<>"]+|www\.[^\s<>"]+', '', regex = True) # Removing hyperlinks from all the tweets
test['text'] = test['text'].str.replace('@[A-Za-z0-9]+', '', regex = True) # Removing usernames from all the tweets.
test['text'] = test['text'].str.replace(r'\B#\w*[a-zA-Z]+\w*', '', regex = True) # Removing hashtags, including the text, from all the tweets
test['text'] = test['text'].str.replace('\d+', '', regex = True) # Removing numbers from all the tweets

for char in special_chars:
    test['text'] = test['text'].str.replace(char, '', regex = True)


In [248]:
# def remove_emoji(string):
#     emoji_pattern = re.compile("["
#                            u"\U0001F600-\U0001F64F"  # emoticons
#                            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
#                            u"\U0001F680-\U0001F6FF"  # transport & map symbols
#                            u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
#                            u"\U00002702-\U000027B0"
#                            u"\U000024C2-\U0001F251"
#                            "]+", flags=re.UNICODE)
#     return emoji_pattern.sub(r'', string)

# for i in range(len(trained['text'])):
#     remove_emoji(trained['text'][i])

In [249]:
trained.head()

Sentiment                                               text
0   neutral                                               said
1  positive            plus added commercials experience tacky
2   neutral             today must mean need take another trip
3  negative   really aggressive blast obnoxious entertainme...
4  negative                               really big bad thing

In [250]:
test.head()

Sentiment                                               text  Predicted
0  negative   phl btv today made deplane its sunday know ma...        NaN
1  negative   things nondelayed flights na get shit togethe...        NaN
2  negative   todayno reason  anyone approve merger other a...        NaN
3   neutral                                look better service        NaN
4  negative   customer service philly deplorable rude  unpr...        NaN

In [251]:
unique_word_in_training = []
for unique_word in range(len(trained['text'])):
    temp = trained['text'][unique_word].split(" ")
    for j in temp:
        if j not in unique_word_in_training:
            unique_word_in_training.append(j)
print(unique_word_in_training)
print(len(unique_word_in_training))

unique_word_in_test = []
for unique_word in range(len(test['text'])):
    temp = test['text'][unique_word].split(" ")
    for j in temp:
        if j not in unique_word_in_test:
            unique_word_in_test.append(j)
print(unique_word_in_test)
print(len(unique_word_in_test))

['', 'said', 'plus', 'added', 'commercials', 'experience', 'tacky', 'today', 'must', 'mean', 'need', 'take', 'another', 'trip', 'really', 'aggressive', 'blast', 'obnoxious', 'entertainment', 'guests', 'faces', 'little', 'recourse', 'big', 'bad', 'thing', 'seriously', 'would', 'pay', 'flight', 'seats', 'playing\nits', 'flying', 'va', 'yes', 'nearly', 'every', 'time', 'fly', 'vx', '“ear', 'worm”', 'won’t', 'go', 'away', 'missed', 'prime', 'opportunity', 'men', 'without', 'hats', 'parody', 'there', 'httpstcomwpggrezp', 'well', 'didnt…but', 'do', 'd', 'amazing', 'arrived', 'hour', 'early', 'good', 'me', 'know', 'suicide', 'second', 'leading', 'cause', 'death', 'among', 'teens', 'lt', 'pretty', 'graphics', 'much', 'better', 'minimal', 'iconography', 'great', 'deal', 'already', 'thinking', 'nd', 'even', 'gone', 'st', 'yet', 'p', 'skies', 'again', 'u', 'travel', 'thanks', 'sfopdx', 'schedule', 'still', 'mia', 'excited', 'first', 'cross', 'country', 'lax', 'mco', 'ive', 'heard', 'nothing', 'th

In [252]:
trained_2D = []
test_2D = []

for text in trained['text']:
    frequency = []
    word = text.split(" ")
    for i in unique_word_in_training:
        frequency.append(word.count(i))
        # print(frequency)
    trained_2D.append(frequency)
    # print(trained_2D)
# print(trained_2D)
# trained_2D.head()

for text in test['text']:
    frequency = []
    word = text.split(" ")
    for i in unique_word_in_training:
        frequency.append(word.count(i))
    test_2D.append(frequency)
# print(test_2D)

In [253]:
# for i in trained_2D:
#     print(i)

In [254]:
# for i in test_2D:
#     print(i)
# trained_2D.shape

In [255]:
print(f"Trained Matrix Dimensions: ({len(trained_2D)}, {len(trained_2D[0])})")
print(f"Test Matrix Dimensions: ({len(test_2D)}, {len(test_2D[0])})")

Trained Matrix Dimensions: (4999, 6739)
Test Matrix Dimensions: (273, 6739)


In [256]:
# def distance(test_row, pos):
#     result = []
#     for a in range(len(trained_2D)):
#         final_distance = 0 
#         for j in range(len(test_row)):
#             distance_trained = trained_2D[i][j]
#             distance_test = test_2D[pos][j]
#             final_distance += (distance_test - distance_trained)**2
#         result.append((final_distance)**(1/2))
#     return result

# for i in range(len(test_2D)):
#     a = distance(test_2D[i], i)
#     print(a)
dists = cdist(test_2D,trained_2D,'euclidean') 
for i in dists:
    print(dists)
dists.shape

[[3.16227766 3.60555128 3.60555128 ... 4.47213595 4.12310563 5.83095189]
 [3.16227766 3.60555128 3.87298335 ... 4.47213595 4.12310563 5.83095189]
 [3.60555128 4.24264069 4.47213595 ... 4.79583152 4.47213595 5.56776436]
 ...
 [3.46410162 3.87298335 4.12310563 ... 4.69041576 4.35889894 6.        ]
 [3.16227766 3.87298335 4.12310563 ... 4.69041576 4.12310563 5.29150262]
 [3.31662479 3.74165739 3.74165739 ... 4.58257569 4.24264069 5.91607978]]
[[3.16227766 3.60555128 3.60555128 ... 4.47213595 4.12310563 5.83095189]
 [3.16227766 3.60555128 3.87298335 ... 4.47213595 4.12310563 5.83095189]
 [3.60555128 4.24264069 4.47213595 ... 4.79583152 4.47213595 5.56776436]
 ...
 [3.46410162 3.87298335 4.12310563 ... 4.69041576 4.35889894 6.        ]
 [3.16227766 3.87298335 4.12310563 ... 4.69041576 4.12310563 5.29150262]
 [3.31662479 3.74165739 3.74165739 ... 4.58257569 4.24264069 5.91607978]]
[[3.16227766 3.60555128 3.60555128 ... 4.47213595 4.12310563 5.83095189]
 [3.16227766 3.60555128 3.87298335 ... 

(273, 4999)

In [257]:
def quick_sort(data, column_index):
    if len(data) <= 1:
        return data
    else:
        pivot = data[0][column_index]
        left = []
        right = []
        for i in range(1, len(data)):
            if data[i][column_index] < pivot:
                left.append(data[i])
            else:
                right.append(data[i])
        return quick_sort(left, column_index) + [data[0]] + quick_sort(right, column_index)

def index_sort(lst):
    indexed_list = []
    for index, element in enumerate(lst):
        indexed_list.append((index, element))
    # print(indexed_list)

    sorted_list = quick_sort(indexed_list, 1)
    result = []
    for i in sorted_list:
        result.append(i[0])
    return result


In [258]:
def mode(lst):
    temp = {}
    for i in lst:
        if i not in temp:
            temp[i] = 1
        else:
            count = temp[i] + 1
            temp[i] = count
    maxim = 0
    label_maxim = []
    for i in temp:
        if temp[i] > maxim:
            maxim = temp[i]
            label_maxim = i
    return label_maxim

In [259]:
def measures(k, test_2D, dists):
    row = 0
    for lst in dists:
        sorted_list = index_sort(lst)
        knn_result = sorted_list[:k]
        
        label_knn = []
        for j in knn_result:
            label = trained['Sentiment'][j]
            label_knn.append(label)
        # print(label_knn)
        
        max_label = mode(label_knn)
        # print(max_label)
        # test.to_csv('Tweets_Test.csv', index=False)
        # test['Predicted'][row] = max_label
        test.loc[row, 'Predicted'] = max_label
        # trained.loc[row, 'Predicted'] = max_label
        # trained.to_csv('./Tweets.csv', index=False)
        test.to_csv('./Tweets_Test.csv', index=False)
        row += 1

        
measures(1, test_2D, dists)